[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/src/v0.8/vrf=lib/chainlink-brownie-contracts/contracts/src/v0.8"]
# remappings = ["@chainlink/contracts/src/v0.8/vrf/interfaces=lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces",
#     "@chainlink/contracts/src/v0.8/vrf=lib/chainlink-brownie-contracts/contracts/src/v0.8"
# ]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
